
services:
#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        - JAR_FILE=build/libs/altioracorp-evaluation-0.0.1-SNAPSHOT.jar
#    ports:
#      - 8080:8080
#    environment:
#      - DATABASE_URL=jdbc:postgresql://db:5432/postgres
#      - DATABASE_USERNAME=postgres
#      - DATABASE_PASSWORD=postgres
#    depends_on:
#      - db
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data_conecta:/var/lib/postgresql/data

volumes:
  postgres_data_conecta: